# Generated by Django 4.2 on 2026-04-18 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin feedback sent back to the doctor'),
        ),
        migrations.CreateModel(
            name='ScanFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='scans/dicom/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_files', to='scans.scan')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
