# Generated by Django 4.2 on 2026-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scan_admin_notes_scanfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='dev_model_file',
            field=models.FileField(blank=True, null=True, upload_to='scans/dev_models/'),
        ),
    ]
